# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 18:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('list', '0003_delete_lista'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='StatusLista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_tarefa', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='lista',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.StatusLista'),
        ),
    ]
