# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 18:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0004_auto_20170918_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lista',
            name='status',
        ),
        migrations.DeleteModel(
            name='StatusLista',
        ),
    ]
