# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 18:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0005_auto_20170918_1507'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lista',
        ),
    ]
