# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0007_lista'),
    ]

    operations = [
        migrations.AddField(
            model_name='lista',
            name='status',
            field=models.CharField(choices=[('P', 'Pendente'), ('F', 'Feita'), ('E', 'Excluida')], default='P', max_length=1),
        ),
    ]
