# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 18:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0008_lista_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lista',
            old_name='descricao',
            new_name='descricao_tarefa',
        ),
        migrations.RenameField(
            model_name='lista',
            old_name='ordem',
            new_name='ordem_tarefa',
        ),
        migrations.RenameField(
            model_name='lista',
            old_name='status',
            new_name='status_tarefa',
        ),
    ]
